DF-2391
PatientPing/terraform-aws-lambda pull request #16
Opened 2021-04-05 14:50 UTC by bugs404

- Add an optional variable that defaults to false and if true gives the codebuild job for the lambda function the ability to invoke the lambda function (for integration testing purposes)

2021-04-05 14:51 UTC, bugs404 commented on lambda_function/ci.tf
> +        "${var.codebuild_can_invoke_lambda ? ",lambda:InvokeFunction" : ""}"
not sure if this is possible or I might have to break this out into separate statements and use the dynamic functionality.

2021-04-05 14:51 UTC, bugs404 commented on lambda_function/ci.tf
> +        "${var.codebuild_can_invoke_lambda ? ",lambda:InvokeFunction" : ""}"
Testing in sandbox currently

2021-04-07 14:06 UTC, eyablonowitz requested changes
Please document this new option in the README and include an example of how it could be used.

2021-04-07 15:06 UTC, eyablonowitz requested changes

2021-04-07 15:06 UTC, eyablonowitz commented on README.md
> +For an example implementation of a lambda-codebuild job setup to conditionally run integration tests see https://github.com/PatientPing/d2p_address_lookup_lambda
This is a public repo/module.  We don't want to put links to private repos in it.  But you could just copy https://github.com/PatientPing/d2p_address_lookup_lambda/blob/DF-2391/buildspec.yml#L16-L19 here to at least hint at how to wire this up.

2021-04-07 15:24 UTC, eyablonowitz approved these changes
lgtm

2021-04-07 16:36 UTC, merged